### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by pat-mw** [zhangks98/eeg-adapt#11]
Hi there, quick question -  which version of Python is this codebase running on? 

I tried installing requirements for Python 3.9.5 but some of the packages forced later versions to be installed than those specified in _**Requirements.txt**_ which in turn lead to some runtime errors when trying to train the models. 

Any guidance would be appreciated :)

**Comment by zhangks98** [comment]
Thanks for your query! iirc, we were using python 3.7 to perform the experiments.
